FROM node:18-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install --omit=dev

# COPY tsconfig.json .eslintrc.json next.config.js ./
# COPY src/ public/ prebuild.js ./
COPY . .

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN  npm run build

EXPOSE 3000
ENV PORT 3000

CMD ["npm", "start"]