# fly.toml app configuration file generated for aws-clerk-nextjs on 2023-06-20T15:23:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aws-clerk-nextjs"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
