services:
- type: web
  name: aws-clerk-nextjs
  env: node
  plan: starter
  buildCommand: npm i; npm run build
  startCommand: npm start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production