services:
- type: web
  name: aws-clerk-nextjs
  env: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production